name: make test
run-name: run unittests
on: [push]
jobs:
  make-test:
    runs-on: ubuntu-latest
    container:
      image: kasterma/poetry:0
    steps:
      - run: python --version
      - run: poetry --version

      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make install
      - run: make test
      - run: make lint
